Upgrade Inventory Page
CoalAI/pos-app pull request #216
Opened 2022-01-28 16:16 UTC by aqsawaheed-8840

Upgrade inventoy page into new inventory page

![Inventory](https://user-images.githubusercontent.com/95912534/149796567-d0d4f1dd-ee60-4415-a335-06caa2171821.jpg)

2022-02-02 10:56 UTC, ammarhaider001 commented
also remove all the console.log statements

2022-02-04 09:44 UTC, ammarhaider001 requested changes

2022-02-04 09:44 UTC, ammarhaider001 commented on aqsa.md
> +
remove this file

2022-02-04 09:44 UTC, ammarhaider001 commented on src/components/admin/Inventory.vue
> +      filter: [1,0,0,0],
remove filter if it is not used.

2022-02-04 09:44 UTC, ammarhaider001 commented on src/components/common-components/Paginator.vue
> -        <a href="#" @click="moveLeft"><strong>&lt;&lt;</strong></a>
dont change this implementation just change the styling.

2022-02-04 09:44 UTC, ammarhaider001 commented on src/components/admin/Inventory.vue
> -  <div class="diff-shadow">
don't remove any existing code. comment out the existing code instead. and mention
// Existing Code Starts Here
// ...
// Existing Code Ends Here

2022-02-04 09:44 UTC, ammarhaider001 commented on src/components/admin/Inventory.vue
> +      console.log(this.search)
remove these console logs

2022-02-07 09:33 UTC, ammarhaiderak approved these changes

2022-02-07 09:38 UTC, merged