273 front end of day close
CoalAI/pos-app pull request #276
Opened 2022-05-16 12:54 UTC by khunshan-coaldev

2022-05-23 12:26 UTC, ammarhaider001 approved these changes

2022-05-23 12:29 UTC, ammarhaider001 requested changes

2022-05-23 12:29 UTC, ammarhaider001 commented on src/components/analytics/EndOfDay.vue
> +      fetchSalesanalytics: ActionTypes.FETCH_SALESANALYTICS,
where have you updated analytics model for new parameters of total_count and total_amount ?

2022-05-27 11:40 UTC, ammarhaider001 submitted a review, later dismissed

2022-05-27 12:04 UTC, forseticameron approved these changes

2022-05-27 12:07 UTC, ammarhaider001 approved these changes

2022-05-27 12:07 UTC, merged