add a dropdown in logout button
CoalAI/pos-app pull request #316
Opened 2022-07-19 23:33 UTC by khunshan-coaldev

- [ ] in addition to logout add settings and reports buttons
- [ ] reports should only be accessed by super admin.

2022-07-19 09:38 UTC, khunshan-coaldev commented
- Reports (Only sup[eradmin)
- Settings (Admin and super admin)

2022-08-05 12:19 UTC, ammarhaider001 requested changes

2022-08-05 12:19 UTC, ammarhaider001 commented on src/components/reports/Basic.vue
> +          <!-- <li :class="tab === 'order' ? 'active-li ab1 tab1' : 'ab1 tab1'" @click="onClickOrder()">
remove commented code.

2022-08-05 12:19 UTC, ammarhaider001 commented on src/components/reports/Basic.vue
> +          <!-- <li :class="tab === 'StockStatement' ? 'active-li ab1 tab2' : 'ab1 tab2'" @click="onClickStockStatement()"
remove commented Code

2022-08-05 12:19 UTC, ammarhaider001 commented on src/components/reports/Report.vue
> +    <!-- commnet out -->
remove commented code

2022-08-05 14:53 UTC, ammarhaider001 approved these changes

2022-08-05 14:54 UTC, merged