feature/expense-integration
CoalAI/pos-app pull request #35
Opened 2021-06-02 09:47 UTC by ammarhaiderak

2021-06-02 10:33 UTC, OmerAli277 requested changes

2021-06-02 10:33 UTC, OmerAli277 commented on src/store/models/transaction.ts
> +    amount?: number | null;
Convert to string.

2021-06-02 10:33 UTC, OmerAli277 commented on src/components/admin/ExpenseSummary.vue
> +    }
Remove this code

2021-06-02 10:55 UTC, OmerAli277 submitted a review, later dismissed

2021-06-03 18:30 UTC, ammarhaiderak commented on src/store/models/transaction.ts
> +    amount?: number | null;
converted

2021-06-03 18:31 UTC, ammarhaiderak commented on src/components/admin/ExpenseSummary.vue
> +    }
done

2021-06-04 10:30 UTC, OmerAli277 approved these changes

2021-06-04 10:31 UTC, mnouman11 approved these changes

2021-06-04 10:31 UTC, merged