feat(productvariant): Barcode and Sale price + Regular Cust Desc
CoalAI/pos-app pull request #79
Opened 2021-06-28 09:39 UTC by ammarhaiderak

closes #74 #70

2021-07-01 09:48 UTC, OmerAli277 requested changes

2021-07-01 09:48 UTC, OmerAli277 commented on src/components/sales/AddEditProduct.vue
>                <col span="1" style="width: 4%;">
Specify percentages

2021-07-01 09:48 UTC, OmerAli277 commented on src/store/models/user.ts
> +}
Add id field

2021-07-01 09:48 UTC, OmerAli277 commented on src/components/sales/Order.vue
> +        user_extra: user_extra
Call user_extra API. Do not change user api.

2021-07-05 08:44 UTC, ammarhaiderak commented on src/components/sales/AddEditProduct.vue
>                <col span="1" style="width: 4%;">
done

2021-07-05 08:44 UTC, ammarhaiderak commented on src/store/models/user.ts
> +}
done

2021-07-05 08:52 UTC, OmerAli277 approved these changes

2021-07-05 10:06 UTC, merged